package com.mphasis.virtual.pax.assitant.entity;

import org.springframework.stereotype.Service;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName = "PassportInfo")
public class PassportInfo {
	
	
	private String id;

	private String surname;
	
	private String name;
	
	private int passportnumber;
	
	private String nationality;
	
	private String dateofBirth;
	
	public PassportInfo() {
		
	}
	

	
	public PassportInfo(String id, String surname, String name, int passportnumber, String nationality,
			String dateofBirth) {
		super();
		this.id = id;
		this.surname = surname;
		this.name = name;
		this.passportnumber = passportnumber;
		this.nationality = nationality;
		this.dateofBirth = dateofBirth;
	}


	
	@DynamoDBHashKey(attributeName = "id")
//	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName = "surname")
	public String getSurname() {
		return surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}
	@DynamoDBAttribute(attributeName="name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	@DynamoDBAttribute(attributeName="passportnumber")
	public int getPassportnumber() {
		return passportnumber;
	}

	public void setPassportnumber(int passportnumber) {
		this.passportnumber = passportnumber;
	}
	@DynamoDBAttribute(attributeName="nationality")
	public String getNationality() {
		return nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}
	@DynamoDBAttribute(attributeName="dateofBirth")
	public String getDateofBirth() {
		return dateofBirth;
	}

	public void setDateofBirth(String dateofBirth) {
		this.dateofBirth = dateofBirth;
	}



	@Override
	public String toString() {
		return "PassportInfo [id=" + id + ", surname=" + surname + ", name=" + name + ", passportnumber="
				+ passportnumber + ", nationality=" + nationality + ", dateofBirth=" + dateofBirth + "]";
	}


}
